version: "3.7"

services:
  konex-app:
    image: konex/konex-crm:latest
    container_name: konex-app
    restart: on-failure
    ports:
      - "3000:3000" # acesso via http://localhost:3000
    environment:
      # =====================
      # AMBIENTE
      # =====================
      RAILS_ENV: production
      TZ: America/Sao_Paulo
      LANGUAGE: "pt-BR"
      DEFAULT_TIMEZONE: "America/Sao_Paulo"

      # =====================
      # BANCO DE DADOS
      # =====================
      DATABASE_URL: postgres://POSTGRES_USER:POSTGRES_PASSWORD@POSTGRES_HOST:5432/konex_crm

      # =====================
      # REDIS
      # =====================
      REDIS_URL: redis://REDIS_USER:REDIS_PASSWORD@REDIS_HOST:6379/0

      # =====================
      # KONEX – CONFIGURAÇÕES
      # =====================
      FRONTEND_URL: "https://konex.seudominio.com"
      GOOD_JOB_EXECUTION_MODE: "external"

      ENABLE_USER_SIGNUP: "false"
      SWAGGER_ENABLED: "true"

      # =====================
      # MOTOR ADMIN
      # =====================
      MOTOR_AUTH_USERNAME: "admin"
      MOTOR_AUTH_PASSWORD: "MUDAR_SENHA"

    depends_on:
      - konex-worker

  konex-worker:
    image: konex/konex-crm:latest
    container_name: konex-worker
    command: bundle exec sidekiq
    restart: on-failure
    environment:
      RAILS_ENV: production
      TZ: America/Sao_Paulo
      LANGUAGE: "pt-BR"
      DEFAULT_TIMEZONE: "America/Sao_Paulo"

      DATABASE_URL: postgres://POSTGRES_USER:POSTGRES_PASSWORD@POSTGRES_HOST:5432/konex_crm
      REDIS_URL: redis://REDIS_USER:REDIS_PASSWORD@REDIS_HOST:6379/0

      GOOD_JOB_EXECUTION_MODE: external
