version: "3.7"

services:
  pgvector:
    image: pgvector/pgvector:pg16
    command: >
      postgres
      -c max_connections=500
      -c shared_buffers=512MB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_pgvector
      POSTGRES_DB: konex_crm
      TZ: America/Sao_Paulo
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - nome_rede_interna
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  pgvector_data:
    external: true
    name: pgvector_data

networks:
  nome_rede_interna:
    external: true
    attachable: true
    name: nome_rede_interna
